#include <rp2350/sio.h>
#include <rp2350/resets.h>
#include <rp2350/io_bank0.h>
#include <rp2350/pads_bank0.h>
#include "servo.h"

#define SERVO_PIN		  8	 
#define SERVO_OFFSET 	-90
#define SERVO_MAX 	(2500 + SERVO_OFFSET)
#define SERVO_ZERO	(1500 + SERVO_OFFSET)
#define SERVO_MIN	(500  + SERVO_OFFSET)
#define SERVO_RESETS 	(RESETS_RESET_IO_BANK0_MASK\
						| RESETS_RESET_PADS_BANK0_MASK\
						| RESETS_RESET_PWM_MASK )


#define CONCAT2 (X,Y)			X ## Y
#define CONCAT3 (X,Y,Z)			X ## Y ## Z
#define PADS_BANK0_GPIO(X) 		CONCAT2(PADS_BANK0_GPIO,X)
#define IO_BANK0_GPIO_CTRL(X)	CONCAT3(IO_BANK0_GPIO,X,_CTRL)


void configure_servo(void){
	
	RESESTS_RESET_CLR = SERVO_RESET;
	while((RESETS_RESET_DONE & SERVO_RESETS)!=SERVO_RESETS)
		continue;

	PAD_BANK0_GPIO(SERVO_PIN) =   
			PADS_BANK0_GPIO(SERVO_PIN)_OD(0) 	|
			PADS_BANK0_GPIO(SERVO_PIN)_IE(0) 	|
			PADS_BANK0_GPIO(SERVO_PIN)_DRIVE(0)	|
			PADS_BANK0_GPIO(SERVO_PIN)_PUE(0)	|
			PADS_BANK0_GPIO(SERVO_PIN)_PDE(0)	|
			PADS_BANK0_GPIO(SERVO_PIN)_SCHMITT(0)|
			PADS_BANK0_GPIO(SERVO_PIN)_SLEWFAST(0); 
	IO_BANK0_GPIO0_CTRL =	
			IO_BANK0_GPIO(SERVO_PIN)_CTRL_IRQOVER(0)|
			IO_BANK0_GPIO(SERVO_PIN)_CTRL_INOVER(0) |
			IO_BANK0_GPIO(SERVO_PIN)_CTRL_OEOVER(0) |
			IO_BANK0_GPIO(SERVO_PIN)_CTRL_OUTOVER(0)|
			IO_BANK0_GPIO(SERVO_PIN)_CTRL_FUNCSEL(4);
	PWM_CH0_DIV = PWM_CH0_DIV_INT(144) | PWM_CH0_DIV_FRAC(0);
	PWM_CH0_TOP = 49999;
	rotate_servo_pin0(0);
	PWM_CH0_CSR =
	PWM_CH0_CSR_PH_ADV(0)
			|PWM_CH0_CSR_PH_RET(0)
			|PWM_CH0_CSR_DIVMODE(0)
			|PWM_CH0_CSR_B_INV(0)
			|PWM_CH0_CSR_A_INV(0)
			|PWM_CH0_CSR_PH_CORRECT(0)
			|PWM_CH0_CSR_EN(1);
}


}


void rotate_servo(int16_t rotate){
	
}


